[package]
name = "notify-schedule"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.35.1"
tokio-cron-scheduler = "0.9.4"
toml = "0.8.8"
